In [12]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [13]:
pima = pd.read_csv(r"D:\The University of Faislabad TUF\NAVTTC AI & ML\Course Content AI\Week 6\diabetes.csv")
pima.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [14]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv(r"D:\The University of Faislabad TUF\NAVTTC AI & ML\Course Content AI\Week 6\diabetes.csv", header=None, names=col_names)

In [15]:
pima.head()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [16]:
pima.sample(30)

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
29,13,145,82,19,110,22.2,0.245,57,0
724,5,117,86,30,105,39.1,0.251,42,0
428,1,181,64,30,180,34.1,0.328,38,1
249,9,124,70,33,402,35.4,0.282,34,0
493,4,99,68,38,0,32.8,0.145,33,0
137,0,100,70,26,50,30.8,0.597,21,0
419,1,83,68,0,0,18.2,0.624,27,0
486,0,135,68,42,250,42.3,0.365,24,1
3,8,183,64,0,0,23.3,0.672,32,1
96,6,144,72,27,228,33.9,0.255,40,0
332,2,87,58,16,52,32.7,0.166,25,0
331,8,118,72,19,0,23.1,1.476,46,0
178,0,129,110,46,130,67.1,0.319,26,1
757,7,137,90,41,0,32,0.391,39,0
32,3,158,76,36,245,31.6,0.851,28,1
36,4,103,60,33,192,24,0.966,33,0
739,2,99,60,17,160,36.6,0.453,21,0
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
367,6,124,72,0,0,27.6,0.368,29,1
720,5,97,76,27,0,35.6,0.378,52,1
261,3,191,68,15,130,30.9,0.299,34,0
388,8,105,100,36,0,43.3,0.239,45,1
175,2,75,64,24,55,29.7,0.37,33,0
394,4,116,72,12,87,22.1,0.463,37,0
112,8,155,62,26,495,34,0.543,46,1
682,0,162,76,36,0,49.6,0.364,26,1
571,3,78,70,0,0,32.5,0.27,39,0
88,2,100,68,25,71,38.5,0.324,26,0
120,4,99,76,15,51,23.2,0.223,21,0
659,11,127,106,0,0,39,0.19,51,0

In [17]:
pima.head()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [20]:
pima.drop(0)

    pregnant glucose  bp skin insulin   bmi pedigree age label
1          6     148  72   35       0  33.6    0.627  50     1
2          1      85  66   29       0  26.6    0.351  31     0
3          8     183  64    0       0  23.3    0.672  32     1
4          1      89  66   23      94  28.1    0.167  21     0
5          0     137  40   35     168  43.1    2.288  33     1
..       ...     ...  ..  ...     ...   ...      ...  ..   ...
764       10     101  76   48     180  32.9    0.171  63     0
765        2     122  70   27       0  36.8     0.34  27     0
766        5     121  72   23     112  26.2    0.245  30     0
767        1     126  60    0       0  30.1    0.349  47     1
768        1      93  70   31       0  30.4    0.315  23     0

[768 rows x 9 columns]

In [21]:
pima.head()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [22]:
pima.drop(index=0, inplace=True)

In [23]:
pima.head()

  pregnant glucose  bp skin insulin   bmi pedigree age label
1        6     148  72   35       0  33.6    0.627  50     1
2        1      85  66   29       0  26.6    0.351  31     0
3        8     183  64    0       0  23.3    0.672  32     1
4        1      89  66   23      94  28.1    0.167  21     0
5        0     137  40   35     168  43.1    2.288  33     1

In [24]:
#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable

In [25]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [33]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [34]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6926406926406926

In [35]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7705627705627706